### ISSUE TITLE
Issues with management of  f1tenth_labs_openrepo and f1tenth_gym_ros volumes in the docker file

### ISSUE THREAD

**Issue by naman-gupta99** [TylerMorton/manager_f1tenth#7]
So, there are a couple of issues that I  have with the current handling of the mounted volumes in the docker-compose.yml.
1. We copy the complete f1tenth_labs_openrepo inside the f1tenth_gym_ros which doesn't make sense. f1tenth_gym_ros is an independent ros package that doesn't need any changes to be done to go through the course.
2. We mount the whole f1tenth_labs_openrepo to the docker container which is not required and increases the size of the final image that we need to upload to the docker repository.
3. Lastly, I can see that we are trying to mount the lab-specific workspace but it isn't working as it is mounting a non-existing directory.

**Comment by TylerMorton** [comment]
Hi Naman,
I agree with the issues you brought up. I will answer each one.

> 1. We copy the complete f1tenth_labs_openrepo inside the f1tenth_gym_ros which doesn't make sense. f1tenth_gym_ros is an independent ros package that doesn't need any changes to be done to go through the course.

My first thought when making this script was to have everything as one source of truth since some of our team were not familiar with CLIs and ROS packages. However, it does make more sense to have a clear separation of concerns.

> 2. We mount the whole f1tenth_labs_openrepo to the docker container which is not required and increases the size of the final image that we need to upload to the docker repository.

Yep this is unnecessary, thank you for addressing this issue.

> 3. Lastly, I can see that we are trying to mount the lab-specific workspace but it isn't working as it is mounting a non-existing directory.

I preferred the separation between my work directory and the directory for the labs... so this was actually my intention. However, this may have simply been my preference since I know that the f1tenth_openlab_repos contains useful code modules and using the same directory keeps the management of directories simple.
